@csrf
<div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
    <div><label for="batch_id" class="block text-sm font-semibold text-ink">Batch</label><select id="batch_id" name="batch_id" required class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm"><option value="">Select a batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((string) old('batch_id', $transportCondition->batch_id ?? '') === (string) $batch->id)>{{ $batch->lot_number }}</option>@endforeach</select>@error('batch_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="traceability_event_id" class="block text-sm font-semibold text-ink">Traceability event ID <span class="font-normal text-ink/45">(optional)</span></label><input id="traceability_event_id" name="traceability_event_id" type="number" value="{{ old('traceability_event_id', $transportCondition->traceability_event_id ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('traceability_event_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="recorded_at" class="block text-sm font-semibold text-ink">Recorded at</label><input id="recorded_at" name="recorded_at" type="datetime-local" required value="{{ old('recorded_at', isset($transportCondition) && $transportCondition->recorded_at ? $transportCondition->recorded_at->format('Y-m-d\TH:i') : '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('recorded_at')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="temperature" class="block text-sm font-semibold text-ink">Temperature (°C)</label><input id="temperature" name="temperature" type="number" step="0.01" min="-50" max="60" required value="{{ old('temperature', $transportCondition->temperature ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('temperature')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="humidity" class="block text-sm font-semibold text-ink">Humidity (%)</label><input id="humidity" name="humidity" type="number" step="0.01" min="0" max="100" value="{{ old('humidity', $transportCondition->humidity ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('humidity')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="duration_minutes" class="block text-sm font-semibold text-ink">Duration (minutes)</label><input id="duration_minutes" name="duration_minutes" type="number" min="0" value="{{ old('duration_minutes', $transportCondition->duration_minutes ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('duration_minutes')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="location" class="block text-sm font-semibold text-ink">Location</label><input id="location" name="location" type="text" value="{{ old('location', $transportCondition->location ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('location')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="notes" class="block text-sm font-semibold text-ink">Notes</label><textarea id="notes" name="notes" rows="4" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">{{ old('notes', $transportCondition->notes ?? '') }}</textarea>@error('notes')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
</div>
<div class="mt-8 flex justify-end gap-3 border-t border-ink/8 pt-6"><a href="{{ route('admin.transport-conditions.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-ink/60">Cancel</a><button class="rounded-xl bg-forest px-5 py-3 text-sm font-semibold text-white">{{ $submitLabel }}</button></div>
