@csrf
<div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
    <div><label for="batch_id" class="block text-sm font-semibold text-ink">Batch</label><select id="batch_id" name="batch_id" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm"><option value="">No batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((string) old('batch_id', $alert->batch_id ?? '') === (string) $batch->id)>{{ $batch->lot_number }}</option>@endforeach</select>@error('batch_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="transport_condition_id" class="block text-sm font-semibold text-ink">Transport condition</label><select id="transport_condition_id" name="transport_condition_id" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm"><option value="">No linked condition</option>@foreach($conditions as $condition)<option value="{{ $condition->id }}" @selected((string) old('transport_condition_id', $alert->transport_condition_id ?? '') === (string) $condition->id)>{{ $condition->batch?->lot_number }} · {{ $condition->recorded_at?->format('d/m/Y H:i') }}</option>@endforeach</select>@error('transport_condition_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="type" class="block text-sm font-semibold text-ink">Type</label><select id="type" name="type" required class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@foreach(\App\Models\Alert::TYPES as $type)<option value="{{ $type }}" @selected(old('type', $alert->type ?? 'temperature') === $type)>{{ ucfirst($type) }}</option>@endforeach</select>@error('type')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="severity" class="block text-sm font-semibold text-ink">Severity</label><select id="severity" name="severity" required class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@foreach(\App\Models\Alert::SEVERITIES as $severity)<option value="{{ $severity }}" @selected(old('severity', $alert->severity ?? 'warning') === $severity)>{{ ucfirst($severity) }}</option>@endforeach</select>@error('severity')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="title" class="block text-sm font-semibold text-ink">Title</label><input id="title" name="title" type="text" required value="{{ old('title', $alert->title ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('title')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="message" class="block text-sm font-semibold text-ink">Message</label><textarea id="message" name="message" rows="4" required class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">{{ old('message', $alert->message ?? '') }}</textarea>@error('message')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="status" class="block text-sm font-semibold text-ink">Status</label><select id="status" name="status" required class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@foreach(\App\Models\Alert::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $alert->status ?? 'open') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="risk_score" class="block text-sm font-semibold text-ink">Risk score</label><input id="risk_score" name="risk_score" type="number" step="0.01" min="0" max="100" value="{{ old('risk_score', $alert->risk_score ?? '') }}" class="mt-2 block w-full rounded-xl border-ink/15 bg-white px-4 py-3 text-sm">@error('risk_score')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
</div>
<div class="mt-8 flex justify-end gap-3 border-t border-ink/8 pt-6"><a href="{{ route('admin.alerts.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-ink/60">Cancel</a><button class="rounded-xl bg-forest px-5 py-3 text-sm font-semibold text-white">{{ $submitLabel }}</button></div>
