<x-dashboard-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-widest text-amber-warm">Cold-chain workspace</p><h2 class="mt-1 font-fraunces text-3xl font-bold text-ink">Alerts</h2><p class="mt-2 text-sm text-ink/55">Review and resolve transport risks.</p></div><a href="{{ route('admin.alerts.create') }}" class="inline-flex items-center justify-center rounded-xl bg-forest px-4 py-3 text-sm font-semibold text-white hover:bg-forest-dark">Create Alert</a></div>
    </x-slot>
    <div class="py-10 sm:py-12"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-medium text-green-800">{{ session('success') }}</div>@endif
        <div class="grid gap-4 sm:grid-cols-3"><x-dashboard.kpi-card label="Open alerts" :value="$openCount" detail="Requires attention" tone="amber" icon="alert" /><x-dashboard.kpi-card label="Critical alerts" :value="$criticalCount" detail="Unresolved critical risks" tone="rose" icon="alert" /><x-dashboard.kpi-card label="Average risk score" :value="number_format($averageRiskScore ?? 0, 2)" detail="Across scored alerts" tone="blue" icon="batch" /></div>
        <section class="rounded-2xl border border-ink/8 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-amber-warm">Dashboard</p><h3 class="mt-1 font-fraunces text-xl font-bold text-ink">Latest cold-chain alerts</h3></div><span class="text-sm text-ink/45">Last 5 alerts</span></div><div class="mt-5 grid gap-3 md:grid-cols-5">@forelse($lastAlerts as $lastAlert)<a href="{{ route('admin.alerts.show', $lastAlert) }}" class="rounded-xl border border-ink/8 p-4 transition hover:bg-cream/50"><p class="truncate text-sm font-semibold text-ink">{{ $lastAlert->title }}</p><p class="mt-2 text-xs text-ink/50">{{ $lastAlert->batch?->lot_number ?? 'No batch' }}</p><div class="mt-3 flex items-center justify-between gap-2"><span class="text-xs font-bold uppercase text-ink/55">{{ $lastAlert->severity }}</span><x-dashboard.status-badge :status="$lastAlert->status" /></div></a>@empty<p class="text-sm text-ink/55">No alerts recorded yet.</p>@endforelse</div></section>
        <div class="rounded-2xl border border-ink/8 bg-white p-4 shadow-sm"><form method="GET" action="{{ route('admin.alerts.index') }}" class="grid grid-cols-1 gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><select name="severity" class="rounded-xl border-ink/10 bg-cream px-4 py-3 text-sm"><option value="">All severities</option>@foreach(\App\Models\Alert::SEVERITIES as $severity)<option value="{{ $severity }}" @selected(request('severity') === $severity)>{{ ucfirst($severity) }}</option>@endforeach</select><select name="status" class="rounded-xl border-ink/10 bg-cream px-4 py-3 text-sm"><option value="">All statuses</option>@foreach(\App\Models\Alert::STATUSES as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><select name="batch_id" class="rounded-xl border-ink/10 bg-cream px-4 py-3 text-sm"><option value="">All batches</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((string) request('batch_id') === (string) $batch->id)>{{ $batch->lot_number }}</option>@endforeach</select><button class="rounded-xl bg-ink px-5 py-3 text-sm font-semibold text-white hover:bg-forest">Filter</button></form></div>
        <div class="overflow-hidden rounded-2xl border border-ink/8 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-ink/8"><thead class="bg-cream/70"><tr><th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-ink/45">Alert</th><th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-ink/45">Batch</th><th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-ink/45">Severity</th><th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-ink/45">Status</th><th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-ink/45">Risk</th><th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wider text-ink/45">Actions</th></tr></thead><tbody class="divide-y divide-ink/8">@forelse($alerts as $alert)@php($severityClass = ['critical' => 'bg-red-100 text-red-800', 'warning' => 'bg-amber-100 text-amber-800', 'info' => 'bg-sky-100 text-sky-800'][$alert->severity] ?? 'bg-ink/8 text-ink/60')<tr class="hover:bg-cream/45"><td class="px-6 py-5"><a href="{{ route('admin.alerts.show', $alert) }}" class="font-semibold text-forest hover:text-amber-warm">{{ $alert->title }}</a><p class="mt-1 text-xs text-ink/50">{{ ucfirst($alert->type) }}</p></td><td class="px-6 py-5 text-sm text-ink/65">{{ $alert->batch?->lot_number ?? '—' }}</td><td class="px-6 py-5"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold uppercase {{ $severityClass }}">{{ $alert->severity }}</span></td><td class="px-6 py-5"><x-dashboard.status-badge :status="$alert->status" /></td><td class="px-6 py-5 text-sm text-ink/65">{{ $alert->risk_score !== null ? $alert->risk_score . ' / 100' : '—' }}</td><td class="whitespace-nowrap px-6 py-5 text-right"><a href="{{ route('admin.alerts.show', $alert) }}" class="mr-3 text-sm font-semibold text-forest">View</a><a href="{{ route('admin.alerts.edit', $alert) }}" class="mr-3 text-sm font-semibold text-ink/55">Edit</a><form method="POST" action="{{ route('admin.alerts.destroy', $alert) }}" class="inline" onsubmit="return confirm('Delete this alert?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="px-6 py-16 text-center"><h3 class="font-fraunces text-lg font-bold text-ink">No alerts found</h3><p class="mt-1 text-sm text-ink/55">No alerts match the selected filters.</p><a href="{{ route('admin.alerts.create') }}" class="mt-5 inline-flex rounded-xl bg-forest px-4 py-2.5 text-sm font-semibold text-white">Create Alert</a></td></tr>@endforelse</tbody></table></div>@if($alerts->hasPages())<div class="border-t border-ink/8 px-6 py-4">{{ $alerts->links() }}</div>@endif</div>
    </div></div>
</x-dashboard-layout>
