<?php
    $statusClasses = ['completed' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300', 'pending' => 'bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300', 'failed' => 'bg-rose-100 text-rose-800 dark:bg-rose-400/15 dark:text-rose-300'];
    $decisionClasses = ['sell' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300', 'donate' => 'bg-sky-100 text-sky-800 dark:bg-sky-400/15 dark:text-sky-300', 'withdraw' => 'bg-rose-100 text-rose-800 dark:bg-rose-400/15 dark:text-rose-300', 'inspect' => 'bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300'];
    $decisionLabels = ['sell' => 'Vente', 'donate' => 'Don', 'withdraw' => 'Retrait', 'inspect' => 'Contrôle'];
    $score = $qualityCheck->quality_score !== null ? (float) $qualityCheck->quality_score : null;
    $freshness = $qualityCheck->freshness_score !== null ? (float) $qualityCheck->freshness_score : null;
    $confidence = $qualityCheck->confidence !== null ? (float) $qualityCheck->confidence : null;
    $factors = is_array($qualityCheck->factors) ? $qualityCheck->factors : [];
?>
<?php if (isset($component)) { $__componentOriginal0de143e5b61900e6d7b990ac144ae3fb = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal0de143e5b61900e6d7b990ac144ae3fb = $attributes; } ?>
<?php $component = App\View\Components\DashboardLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('dashboard-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\DashboardLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-amber-warm">Quality workspace</p><h1 class="mt-1 font-fraunces text-3xl font-bold text-ink dark:text-white">Résultat de l'analyse</h1><p class="mt-2 text-sm text-ink/55 dark:text-white/55">Analyse #<?php echo e($qualityCheck->id); ?> · <?php echo e($qualityCheck->created_at?->format('d M Y, H:i')); ?></p></div> <?php $__env->endSlot(); ?>
    <div class="mx-auto max-w-7xl space-y-6">
        <?php if(session('success')): ?><div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-300/20 dark:bg-emerald-400/10 dark:text-emerald-300"><?php echo e(session('success')); ?></div><?php endif; ?>
        <?php if($qualityCheck->status === 'pending'): ?><div class="flex items-center gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900 dark:border-amber-300/20 dark:bg-amber-400/10 dark:text-amber-200"><div class="h-10 w-10 animate-pulse rounded-full bg-amber-warm/20 p-2"><svg class="h-6 w-6 text-amber-warm" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 6v6l4 2"/><circle cx="12" cy="12" r="9"/></svg></div><div><p class="font-semibold">Analyse en cours via Ollama…</p><p class="mt-1 text-sm opacity-80">Rafraîchissez dans quelques secondes.</p></div></div><?php endif; ?>
        <div class="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
            <div class="space-y-6">
                <div class="overflow-hidden rounded-2xl border border-ink/8 bg-white shadow-sm dark:border-white/10 dark:bg-[#1E3527]"><div class="flex max-h-[420px] min-h-[240px] w-full items-center justify-center bg-cream p-4 sm:p-6 dark:bg-[#16281E]"><?php if($qualityCheck->image_path): ?><img src="<?php echo e(asset('storage/' . $qualityCheck->image_path)); ?>" alt="Image analysée" class="max-h-[380px] max-w-full rounded-xl object-contain shadow-sm"><?php else: ?><div class="flex h-full min-h-[220px] w-full items-center justify-center text-ink/30 dark:text-white/30">Aucune image</div><?php endif; ?></div><div class="p-6"><p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-warm">Produit</p><h2 class="mt-2 font-fraunces text-2xl font-bold text-ink dark:text-white"><?php echo e($qualityCheck->product?->name ?? 'Produit supprimé'); ?></h2><p class="mt-1 text-sm text-ink/55 dark:text-white/55"><?php echo e($qualityCheck->product?->category ?? 'Catégorie non renseignée'); ?></p><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-ink/50 dark:text-white/50">Créé par</dt><dd class="font-semibold text-ink dark:text-white"><?php echo e($qualityCheck->creator?->name ?? 'Système'); ?></dd></div><div class="flex justify-between gap-4"><dt class="text-ink/50 dark:text-white/50">Date</dt><dd class="font-semibold text-ink dark:text-white"><?php echo e($qualityCheck->created_at?->format('d/m/Y H:i')); ?></dd></div></dl></div></div>
                <div class="flex flex-wrap gap-3"><a href="<?php echo e(route('admin.quality-checks.index')); ?>" class="inline-flex items-center rounded-xl border border-ink/10 px-4 py-2.5 text-sm font-semibold text-ink/70 hover:bg-cream dark:border-white/10 dark:text-white/70 dark:hover:bg-white/5">Retour aux analyses</a><form action="<?php echo e(route('admin.quality-checks.destroy', $qualityCheck)); ?>" method="POST" onsubmit="return confirm('Supprimer cette analyse ?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700 hover:bg-rose-50 dark:border-rose-300/20 dark:text-rose-300 dark:hover:bg-rose-400/10">Supprimer</button></form></div>
            </div>
            <div class="space-y-6">
                <div class="rounded-2xl border border-ink/8 bg-white p-6 shadow-[0_18px_45px_-32px_rgba(31,61,46,0.8)] dark:border-white/10 dark:bg-[#1E3527]">
                    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-warm">Analyse qualité</p><h2 class="mt-1 font-fraunces text-2xl font-bold text-ink dark:text-white">Résultats</h2></div><span class="rounded-full px-3 py-1.5 text-xs font-semibold <?php echo e($statusClasses[$qualityCheck->status] ?? 'bg-ink/10 text-ink/60 dark:bg-white/10 dark:text-white/60'); ?>"><?php echo e(ucfirst($qualityCheck->status)); ?></span></div>
                    <div class="mt-7 grid gap-4 sm:grid-cols-2"><div class="rounded-2xl bg-cream p-5 dark:bg-[#16281E]"><div class="flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-wider text-ink/50 dark:text-white/50">Quality score</span><span class="text-xs font-semibold text-forest dark:text-emerald-300">Qualité globale</span></div><p class="mt-3 font-fraunces text-4xl font-bold text-ink dark:text-white"><?php echo e($score !== null ? number_format($score, 1) . '%' : '—'); ?></p><div class="mt-4 h-2.5 overflow-hidden rounded-full bg-ink/10 dark:bg-white/10"><div class="h-full rounded-full bg-gradient-to-r from-forest to-emerald-400 transition-all" style="width: <?php echo e(min(max($score ?? 0, 0), 100)); ?>%"></div></div><p class="mt-2 text-xs text-ink/45 dark:text-white/45">Indice de qualité estimé</p></div><div class="rounded-2xl bg-cream p-5 dark:bg-[#16281E]"><div class="flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-wider text-ink/50 dark:text-white/50">Freshness score</span><span class="text-xs font-semibold text-sky-700 dark:text-sky-300">Fraîcheur</span></div><p class="mt-3 font-fraunces text-4xl font-bold text-ink dark:text-white"><?php echo e($freshness !== null ? number_format($freshness, 1) . '%' : '—'); ?></p><div class="mt-4 h-2.5 overflow-hidden rounded-full bg-ink/10 dark:bg-white/10"><div class="h-full rounded-full bg-gradient-to-r from-sky-700 to-sky-400" style="width: <?php echo e(min(max($freshness ?? 0, 0), 100)); ?>%"></div></div><p class="mt-2 text-xs text-ink/45 dark:text-white/45">Indice de fraîcheur visuelle</p></div></div>
                    <div class="mt-6 rounded-2xl border border-ink/8 bg-cream/70 p-5 dark:border-white/10 dark:bg-[#16281E]"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-ink/50 dark:text-white/50">Décision recommandée</p><p class="mt-1 text-sm text-ink/55 dark:text-white/55">Issue proposée par le moteur qualité</p></div><span class="rounded-full px-5 py-2.5 text-base font-bold shadow-sm <?php echo e($decisionClasses[$qualityCheck->decision] ?? 'bg-ink/10 text-ink/60 dark:bg-white/10 dark:text-white/60'); ?>"><?php echo e($decisionLabels[$qualityCheck->decision] ?? 'En attente'); ?></span></div><div class="mt-4 flex items-center justify-between text-xs text-ink/50 dark:text-white/50"><span>Confiance de l'analyse</span><span class="font-semibold text-ink dark:text-white"><?php echo e($confidence !== null ? number_format($confidence, 1) . '%' : '—'); ?></span></div></div>
                </div>
                <div class="rounded-2xl border border-amber-200/70 bg-amber-50/70 p-6 shadow-sm dark:border-amber-300/15 dark:bg-amber-400/10"><div class="flex gap-4"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-warm/15 text-amber-warm"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3 4 7v5c0 4.5 3.4 7.8 8 9 4.6-1.2 8-4.5 8-9V7l-8-4Z"/><path d="M9 12h6M12 9v6"/></svg></div><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-800/70 dark:text-amber-200/70">Lecture de l'IA</p><p class="mt-2 text-[15px] leading-7 text-amber-950/80 dark:text-amber-100/80"><?php echo e($qualityCheck->explanation ?: 'L’explication sera disponible une fois l’analyse terminée.'); ?></p></div></div><?php if(count($factors)): ?><div class="mt-5 flex flex-wrap gap-2 border-t border-amber-900/10 pt-4 dark:border-amber-100/10"><?php $__currentLoopData = $factors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $factor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span class="rounded-full border border-forest/15 bg-white/70 px-3 py-1.5 text-xs font-semibold text-forest shadow-sm dark:border-emerald-300/20 dark:bg-emerald-300/10 dark:text-emerald-200"><?php echo e(is_array($factor) ? ($factor['label'] ?? json_encode($factor)) : $factor); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?></div>
            </div>
        </div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal0de143e5b61900e6d7b990ac144ae3fb)): ?>
<?php $attributes = $__attributesOriginal0de143e5b61900e6d7b990ac144ae3fb; ?>
<?php unset($__attributesOriginal0de143e5b61900e6d7b990ac144ae3fb); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal0de143e5b61900e6d7b990ac144ae3fb)): ?>
<?php $component = $__componentOriginal0de143e5b61900e6d7b990ac144ae3fb; ?>
<?php unset($__componentOriginal0de143e5b61900e6d7b990ac144ae3fb); ?>
<?php endif; ?>
<?php /**PATH C:\Users\mdain\nutritrace1\nutritrace\resources\views\admin\quality-checks\show.blade.php ENDPATH**/ ?>