@php
    $statusClasses = ['completed' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300', 'pending' => 'bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300', 'failed' => 'bg-rose-100 text-rose-800 dark:bg-rose-400/15 dark:text-rose-300'];
    $decisionClasses = ['sell' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-400/15 dark:text-emerald-300', 'donate' => 'bg-sky-100 text-sky-800 dark:bg-sky-400/15 dark:text-sky-300', 'withdraw' => 'bg-rose-100 text-rose-800 dark:bg-rose-400/15 dark:text-rose-300', 'inspect' => 'bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-300'];
    $decisionLabels = ['sell' => 'Vente', 'donate' => 'Don', 'withdraw' => 'Retrait', 'inspect' => 'Contrôle'];
    $score = $qualityCheck->quality_score !== null ? (float) $qualityCheck->quality_score : null;
    $freshness = $qualityCheck->freshness_score !== null ? (float) $qualityCheck->freshness_score : null;
    $confidence = $qualityCheck->confidence !== null ? (float) $qualityCheck->confidence : null;
    $factors = is_array($qualityCheck->factors) ? $qualityCheck->factors : [];
@endphp
<x-dashboard-layout>
    <x-slot name="header"><div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-amber-warm">Quality workspace</p><h1 class="mt-1 font-fraunces text-3xl font-bold text-ink dark:text-white">Résultat de l'analyse</h1><p class="mt-2 text-sm text-ink/55 dark:text-white/55">Analyse #{{ $qualityCheck->id }} · {{ $qualityCheck->created_at?->format('d M Y, H:i') }}</p></div></x-slot>
    <div class="mx-auto max-w-7xl space-y-6">
        @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-300/20 dark:bg-emerald-400/10 dark:text-emerald-300">{{ session('success') }}</div>@endif
        @if($qualityCheck->status === 'pending')<div class="flex items-center gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900 dark:border-amber-300/20 dark:bg-amber-400/10 dark:text-amber-200"><div class="h-10 w-10 animate-pulse rounded-full bg-amber-warm/20 p-2"><svg class="h-6 w-6 text-amber-warm" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 6v6l4 2"/><circle cx="12" cy="12" r="9"/></svg></div><div><p class="font-semibold">Analyse en cours via Ollama…</p><p class="mt-1 text-sm opacity-80">Rafraîchissez dans quelques secondes.</p></div></div>@endif
        <div class="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
            <div class="space-y-6">
                <div class="overflow-hidden rounded-2xl border border-ink/8 bg-white shadow-sm dark:border-white/10 dark:bg-[#1E3527]">
                    <div class="flex max-h-[420px] min-h-[240px] w-full items-center justify-center bg-cream p-4 sm:p-6 dark:bg-[#16281E]">
                        @if($qualityCheck->image_path && \Illuminate\Support\Facades\Storage::disk('public')->exists(ltrim($qualityCheck->image_path, '/')))
                            <img src="{{ asset('storage/quality-checks-public/' . basename(ltrim($qualityCheck->image_path, '/'))) }}" alt="Image analysée" class="max-h-[380px] max-w-full rounded-xl object-contain shadow-sm">
                        @else
                            <div class="flex h-full min-h-[220px] w-full items-center justify-center text-ink/30 dark:text-white/30">Aucune image</div>
                        @endif
                    </div>
                    <div class="p-6">
                        <p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-warm">Produit</p>
                        <h2 class="mt-2 font-fraunces text-2xl font-bold text-ink dark:text-white">{{ $qualityCheck->product?->name ?? 'Produit supprimé' }}</h2>
                        <p class="mt-1 text-sm text-ink/55 dark:text-white/55">{{ $qualityCheck->product?->category ?? 'Catégorie non renseignée' }}</p>
                        <div class="mt-5 flex min-h-[180px] items-center justify-center rounded-xl bg-cream p-4 dark:bg-[#16281E]">
                            @if($qualityCheck->product && !empty($qualityCheck->product->image_url))
                                <img src="{{ $qualityCheck->product->image_url }}" alt="{{ $qualityCheck->product->name }}" class="max-h-[320px] w-full rounded-xl object-contain">
                            @else
                                <span class="font-fraunces text-5xl font-semibold text-forest/25 dark:text-emerald-300/25">{{ strtoupper(substr($qualityCheck->product?->name ?? '?', 0, 1)) }}</span>
                            @endif
                        </div>
                        <dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-ink/50 dark:text-white/50">Créé par</dt><dd class="font-semibold text-ink dark:text-white">{{ $qualityCheck->creator?->name ?? 'Système' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink/50 dark:text-white/50">Date</dt><dd class="font-semibold text-ink dark:text-white">{{ $qualityCheck->created_at?->format('d/m/Y H:i') }}</dd></div></dl>
                    </div>
                </div>
                <div class="flex flex-wrap gap-3"><a href="{{ route('admin.quality-checks.index') }}" class="inline-flex items-center rounded-xl border border-ink/10 px-4 py-2.5 text-sm font-semibold text-ink/70 hover:bg-cream dark:border-white/10 dark:text-white/70 dark:hover:bg-white/5">Retour aux analyses</a><form action="{{ route('admin.quality-checks.destroy', $qualityCheck) }}" method="POST" onsubmit="return confirm('Supprimer cette analyse ?')">@csrf @method('DELETE')<button class="rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700 hover:bg-rose-50 dark:border-rose-300/20 dark:text-rose-300 dark:hover:bg-rose-400/10">Supprimer</button></form></div>
            </div>
            <div class="space-y-6">
                <div class="rounded-2xl border border-ink/8 bg-white p-6 shadow-[0_18px_45px_-32px_rgba(31,61,46,0.8)] dark:border-white/10 dark:bg-[#1E3527]">
                    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-warm">Analyse qualité</p><h2 class="mt-1 font-fraunces text-2xl font-bold text-ink dark:text-white">Résultats</h2></div><span class="rounded-full px-3 py-1.5 text-xs font-semibold {{ $statusClasses[$qualityCheck->status] ?? 'bg-ink/10 text-ink/60 dark:bg-white/10 dark:text-white/60' }}">{{ ucfirst($qualityCheck->status) }}</span></div>
                    <div class="mt-7 grid gap-4 sm:grid-cols-2"><div class="rounded-2xl bg-cream p-5 dark:bg-[#16281E]"><div class="flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-wider text-ink/50 dark:text-white/50">Quality score</span><span class="text-xs font-semibold text-forest dark:text-emerald-300">Qualité globale</span></div><p class="mt-3 font-fraunces text-4xl font-bold text-ink dark:text-white">{{ $score !== null ? number_format($score, 1) . '%' : '—' }}</p><div class="mt-4 h-2.5 overflow-hidden rounded-full bg-ink/10 dark:bg-white/10"><div class="h-full rounded-full bg-gradient-to-r from-forest to-emerald-400 transition-all" style="width: {{ min(max($score ?? 0, 0), 100) }}%"></div></div><p class="mt-2 text-xs text-ink/45 dark:text-white/45">Indice de qualité estimé</p></div><div class="rounded-2xl bg-cream p-5 dark:bg-[#16281E]"><div class="flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-wider text-ink/50 dark:text-white/50">Freshness score</span><span class="text-xs font-semibold text-sky-700 dark:text-sky-300">Fraîcheur</span></div><p class="mt-3 font-fraunces text-4xl font-bold text-ink dark:text-white">{{ $freshness !== null ? number_format($freshness, 1) . '%' : '—' }}</p><div class="mt-4 h-2.5 overflow-hidden rounded-full bg-ink/10 dark:bg-white/10"><div class="h-full rounded-full bg-gradient-to-r from-sky-700 to-sky-400" style="width: {{ min(max($freshness ?? 0, 0), 100) }}%"></div></div><p class="mt-2 text-xs text-ink/45 dark:text-white/45">Indice de fraîcheur visuelle</p></div></div>
                    <div class="mt-6 rounded-2xl border border-ink/8 bg-cream/70 p-5 dark:border-white/10 dark:bg-[#16281E]"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-ink/50 dark:text-white/50">Décision recommandée</p><p class="mt-1 text-sm text-ink/55 dark:text-white/55">Issue proposée par le moteur qualité</p></div><span class="rounded-full px-5 py-2.5 text-base font-bold shadow-sm {{ $decisionClasses[$qualityCheck->decision] ?? 'bg-ink/10 text-ink/60 dark:bg-white/10 dark:text-white/60' }}">{{ $decisionLabels[$qualityCheck->decision] ?? 'En attente' }}</span></div><div class="mt-4 flex items-center justify-between text-xs text-ink/50 dark:text-white/50"><span>Confiance de l'analyse</span><span class="font-semibold text-ink dark:text-white">{{ $confidence !== null ? number_format($confidence, 1) . '%' : '—' }}</span></div></div>
                </div>
                <div class="rounded-2xl border border-amber-200/70 bg-amber-50/70 p-6 shadow-sm dark:border-amber-300/15 dark:bg-amber-400/10"><div class="flex gap-4"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-warm/15 text-amber-warm"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3 4 7v5c0 4.5 3.4 7.8 8 9 4.6-1.2 8-4.5 8-9V7l-8-4Z"/><path d="M9 12h6M12 9v6"/></svg></div><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-amber-800/70 dark:text-amber-200/70">Lecture de l'IA</p><p class="mt-2 text-[15px] leading-7 text-amber-950/80 dark:text-amber-100/80">{{ $qualityCheck->explanation ?: 'L’explication sera disponible une fois l’analyse terminée.' }}</p></div></div>@if(count($factors))<div class="mt-5 flex flex-wrap gap-2 border-t border-amber-900/10 pt-4 dark:border-amber-100/10">@foreach($factors as $factor)<span class="rounded-full border border-forest/15 bg-white/70 px-3 py-1.5 text-xs font-semibold text-forest shadow-sm dark:border-emerald-300/20 dark:bg-emerald-300/10 dark:text-emerald-200">{{ is_array($factor) ? ($factor['label'] ?? json_encode($factor)) : $factor }}</span>@endforeach</div>@endif</div>
            </div>
        </div>
    </div>
</x-dashboard-layout>
